openapi: 3.0.3
info:
  title: RepMotivatedSeller API
  version: 1.0.0
  description: API for foreclosure assistance and real estate services
  contact:
    name: RepMotivatedSeller Support
    email: support@repmotivatedseller.shoprealestatespace.org

servers:
  - url: https://repmotivatedseller.shoprealestatespace.org/api
    description: Production API
  - url: http://localhost:5173/api
    description: Development API

paths:
  /create-checkout-session:
    post:
      summary: Create Stripe checkout session
      tags:
        - Payments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - priceId
                - userId
                - planId
              properties:
                priceId:
                  type: string
                  pattern: "^price_[a-zA-Z0-9_]+$"
                  example: "price_1234567890"
                userId:
                  type: string
                  format: uuid
                planId:
                  type: string
                  enum: ["free", "professional", "enterprise"]
                successUrl:
                  type: string
                  format: uri
                cancelUrl:
                  type: string
                  format: uri
      responses:
        200:
          description: Checkout session created
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionId:
                    type: string
        400:
          description: Invalid request
        401:
          description: Unauthorized

  /foreclosure-form:
    post:
      summary: Submit foreclosure assistance form
      tags:
        - Forms
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - propertyAddress
                - loanStatus
                - contactName
                - contactPhone
                - contactEmail
              properties:
                propertyAddress:
                  type: string
                  minLength: 10
                  maxLength: 200
                loanStatus:
                  type: string
                  enum: ["current", "behind", "foreclosure"]
                contactName:
                  type: string
                  minLength: 2
                  maxLength: 100
                contactPhone:
                  type: string
                  pattern: "^\\([0-9]{3}\\)\\s[0-9]{3}-[0-9]{4}$"
                contactEmail:
                  type: string
                  format: email
      responses:
        200:
          description: Form submitted successfully
        400:
          description: Validation error

  /health:
    get:
      summary: Health check endpoint
      responses:
        200:
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT