import React, { useMemo, useState } from "react";
import { CheckCircle, Download, FileText, Printer } from "lucide-react";

interface WholesaleFormData {
  sellerName: string;
  sellerAddress: string;
  buyerName: string;
  buyerAddress: string;
  propertyAddress: string;
  purchasePrice: string;
  depositAmount: string;
  assignmentFee: string;
  closingDate: string;
}

const initialWholesaleData: WholesaleFormData = {
  sellerName: "",
  sellerAddress: "",
  buyerName: "",
  buyerAddress: "",
  propertyAddress: "",
  purchasePrice: "",
  depositAmount: "",
  assignmentFee: "",
  closingDate: "",
};

function formatCurrency(value: string): string {
  const numeric = Number.parseFloat(value || "0");
  if (Number.isNaN(numeric)) return "$0";
  return `$${numeric.toLocaleString()}`;
}

function buildWholesaleHtml(data: WholesaleFormData): string {
  return `<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; padding: 40px; }
    h1 { text-align: center; color: #1e40af; }
    .section { margin: 20px 0; }
    .signature-line { margin-top: 40px; border-top: 1px solid #000; width: 300px; }
  </style>
</head>
<body>
  <h1>WHOLESALE REAL ESTATE PURCHASE AGREEMENT</h1>
  <div class="section">
    <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
  </div>
  <div class="section">
    <h3>SELLER INFORMATION</h3>
    <p><strong>Name:</strong> ${data.sellerName}</p>
    <p><strong>Address:</strong> ${data.sellerAddress}</p>
  </div>
  <div class="section">
    <h3>BUYER INFORMATION</h3>
    <p><strong>Name:</strong> ${data.buyerName} and/or assigns</p>
    <p><strong>Address:</strong> ${data.buyerAddress}</p>
  </div>
  <div class="section">
    <h3>PROPERTY</h3>
    <p><strong>Address:</strong> ${data.propertyAddress}</p>
  </div>
  <div class="section">
    <h3>PURCHASE TERMS</h3>
    <p><strong>Purchase Price:</strong> ${formatCurrency(data.purchasePrice)}</p>
    <p><strong>Earnest Money Deposit:</strong> ${formatCurrency(data.depositAmount)}</p>
    <p><strong>Assignment Fee:</strong> ${formatCurrency(data.assignmentFee)}</p>
    <p><strong>Closing Date:</strong> ${data.closingDate}</p>
  </div>
  <div class="section">
    <h3>ASSIGNMENT RIGHTS</h3>
    <p>Buyer may assign this contract to another party without the consent of the Seller. The assignment fee of ${formatCurrency(data.assignmentFee)} shall be paid to Buyer at closing.</p>
  </div>
  <div class="section">
    <h3>CONTINGENCIES</h3>
    <p>This agreement is contingent upon:</p>
    <ul>
      <li>Buyer inspection and approval</li>
      <li>Clear and marketable title</li>
      <li>Buyer ability to secure financing or assign</li>
    </ul>
  </div>
  <div class="section" style="display:flex; justify-content: space-between; margin-top: 60px;">
    <div>
      <div class="signature-line"></div>
      <p>Seller Signature / Date</p>
    </div>
    <div>
      <div class="signature-line"></div>
      <p>Buyer Signature / Date</p>
    </div>
  </div>
  <div class="section" style="margin-top: 40px; border-top: 2px solid #000; padding-top: 20px;">
    <p><strong>IMPORTANT NOTICE:</strong> This is a legally binding contract. Review with legal counsel before signing.</p>
    <p style="font-size: 12px; color: #666;">Generated by RepMotivatedSeller Contract Generator on ${new Date().toLocaleString()}</p>
  </div>
</body>
</html>`;
}

export const WholesaleContractForm: React.FC = () => {
  const [formData, setFormData] =
    useState<WholesaleFormData>(initialWholesaleData);
  const [generatedHtml, setGeneratedHtml] = useState<string | null>(null);

  const isComplete = useMemo(() => {
    return Object.values(formData).every((value) => value.trim().length > 0);
  }, [formData]);

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>,
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const generate = () => {
    setGeneratedHtml(buildWholesaleHtml(formData));
  };

  const download = () => {
    if (!generatedHtml) return;
    const blob = new Blob([generatedHtml], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "wholesale-contract.html";
    a.click();
    URL.revokeObjectURL(url);
  };

  const printDoc = () => {
    if (!generatedHtml) return;
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;
    printWindow.document.write(generatedHtml);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="max-w-4xl mx-auto bg-white rounded-2xl shadow-lg p-8 border border-gray-200">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <FileText className="w-8 h-8 text-blue-600" />
          <div>
            <h2 className="text-2xl font-bold text-gray-900">
              Wholesale Real Estate Contract
            </h2>
            <p className="text-gray-600">
              Assignment-friendly purchase agreement with key contingencies
            </p>
          </div>
        </div>
        {isComplete && generatedHtml && (
          <span className="inline-flex items-center text-sm text-green-700 bg-green-50 px-3 py-1 rounded-full border border-green-200">
            <CheckCircle className="w-4 h-4 mr-1" /> Ready to export
          </span>
        )}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700">
            Seller Name
          </label>
          <input
            name="sellerName"
            value={formData.sellerName}
            onChange={handleChange}
            className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2"
            placeholder="John Seller"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700">
            Seller Address
          </label>
          <input
            name="sellerAddress"
            value={formData.sellerAddress}
            onChange={handleChange}
            className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2"
            placeholder="123 Main St, City, ST"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700">
            Buyer Name
          </label>
          <input
            name="buyerName"
            value={formData.buyerName}
            onChange={handleChange}
            className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2"
            placeholder="Jane Buyer"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700">
            Buyer Address
          </label>
          <input
            name="buyerAddress"
            value={formData.buyerAddress}
            onChange={handleChange}
            className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2"
            placeholder="456 Elm St, City, ST"
          />
        </div>
        <div className="md:col-span-2">
          <label className="block text-sm font-medium text-gray-700">
            Property Address
          </label>
          <input
            name="propertyAddress"
            value={formData.propertyAddress}
            onChange={handleChange}
            className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2"
            placeholder="789 Oak Ave, City, ST"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700">
            Purchase Price
          </label>
          <input
            name="purchasePrice"
            value={formData.purchasePrice}
            onChange={handleChange}
            className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2"
            placeholder="150000"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700">
            Earnest Money Deposit
          </label>
          <input
            name="depositAmount"
            value={formData.depositAmount}
            onChange={handleChange}
            className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2"
            placeholder="5000"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700">
            Assignment Fee
          </label>
          <input
            name="assignmentFee"
            value={formData.assignmentFee}
            onChange={handleChange}
            className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2"
            placeholder="10000"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700">
            Closing Date
          </label>
          <input
            name="closingDate"
            value={formData.closingDate}
            onChange={handleChange}
            className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2"
            placeholder="2026-03-15"
          />
        </div>
      </div>

      <div className="flex flex-wrap gap-3 mt-8">
        <button
          type="button"
          onClick={generate}
          className="inline-flex items-center px-4 py-2 rounded-lg bg-blue-600 text-white hover:bg-blue-700"
        >
          <FileText className="w-4 h-4 mr-2" />
          Generate Contract
        </button>
        <button
          type="button"
          onClick={download}
          disabled={!generatedHtml}
          className="inline-flex items-center px-4 py-2 rounded-lg bg-green-600 text-white hover:bg-green-700 disabled:opacity-50"
        >
          <Download className="w-4 h-4 mr-2" />
          Download
        </button>
        <button
          type="button"
          onClick={printDoc}
          disabled={!generatedHtml}
          className="inline-flex items-center px-4 py-2 rounded-lg bg-gray-700 text-white hover:bg-gray-800 disabled:opacity-50"
        >
          <Printer className="w-4 h-4 mr-2" />
          Print
        </button>
      </div>
    </div>
  );
};
